"""init

Revision ID: 485ea35e57cc
Revises: 
Create Date: 2026-04-19 15:47:19.516655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '485ea35e57cc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_alarm_id', sa.String(length=100), nullable=True),
    sa.Column('source_system', sa.String(length=100), nullable=True),
    sa.Column('tag', sa.String(length=200), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('criticality', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=True),
    sa.Column('plant', sa.String(length=100), nullable=True),
    sa.Column('area', sa.String(length=100), nullable=True),
    sa.Column('equipment', sa.String(length=100), nullable=True),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('ack_time', sa.DateTime(), nullable=True),
    sa.Column('clear_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_alarm_id', 'event_time', 'tag', name='uq_alarm_business_key')
    )
    op.create_index('ix_alarms_criticality', 'alarms', ['criticality'], unique=False)
    op.create_index('ix_alarms_criticality_event_time', 'alarms', ['criticality', 'event_time'], unique=False)
    op.create_index('ix_alarms_event_time', 'alarms', ['event_time'], unique=False)
    op.create_index('ix_alarms_tag', 'alarms', ['tag'], unique=False)
    op.create_index('ix_alarms_tag_event_time', 'alarms', ['tag', 'event_time'], unique=False)
    op.create_table('ingestion_batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_file_name', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('inserted_rows', sa.Integer(), nullable=False),
    sa.Column('rejected_rows', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alarm_rejections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['ingestion_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alarm_rejections')
    op.drop_table('ingestion_batches')
    op.drop_index('ix_alarms_tag_event_time', table_name='alarms')
    op.drop_index('ix_alarms_tag', table_name='alarms')
    op.drop_index('ix_alarms_event_time', table_name='alarms')
    op.drop_index('ix_alarms_criticality_event_time', table_name='alarms')
    op.drop_index('ix_alarms_criticality', table_name='alarms')
    op.drop_table('alarms')
    # ### end Alembic commands ###
